@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cool.furry.mc.neoforge.projectexpansion.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;