modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="projectexpansion"
version="${file.jarVersion}"
displayName="Project Expansion"
updateJSONURL="https://raw.githubusercontent.com/DonovanDMC/ProjectExpansion/1.18/updates.json"
displayURL="https://github.com/DonovanDMC/ProjectExpansion"
logoFile="icon.png"
credits="sinkillerj for ProjectE"
authors="Donovan_DMC"
description='''
An unofficial expansion of ProjectE.
'''
[[dependencies.projectexpansion]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.projectexpansion]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2]"
   ordering="NONE"
   side="BOTH"
[[dependencies.projectexpansion]]
   modId="projecte"
   mandatory=true
   versionRange="*"
   ordering="AFTER"
   side="BOTH"
