@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cool.furry.mc.forge.projectexpansion.container.slots;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;