@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cool.furry.mc.forge.projectexpansion.enchantments;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;