@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cool.furry.mc.forge.projectexpansion.enchantments;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;